In [2]:
import pandas as pd
import numpy as np

In [9]:
pd.__version__

'2.2.2'

In [3]:
df = pd.read_csv('/home/mike/Developer/ml-engineer-zoomcamp/01-intro/data/laptops.csv')

In [10]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB
None


In [16]:
print(df['Brand'].value_counts())
print(df['Brand'].nunique())

Brand
Asus                415
HP                  368
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Deep Gaming           8
Primux                8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64
27


In [4]:
print(df.head())

                                              Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.

In [17]:
print(df.isnull().sum())

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64


In [24]:
# print max price for dell
print(df[df['Brand'] == 'Dell']['Final Price'].max())
print(df['Screen'].median())

3936.0
15.6


In [26]:
df['Screen'] = df['Screen'].fillna(df['Screen'].mode()[0])
print(df['Screen'].median())

15.6


In [5]:
innjoo_df = df[df['Brand'] == 'Innjoo']
X = innjoo_df[['Screen', 'Storage', 'RAM']].to_numpy()
XTX = X.T.dot(X)
print(XTX)


[[1.28196e+03 1.73952e+04 5.59800e+02]
 [1.73952e+04 3.68640e+05 8.32000e+03]
 [5.59800e+02 8.32000e+03 2.52000e+02]]


In [6]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [7]:
w = np.linalg.inv(XTX).dot(X.T).dot(y)

In [8]:
print(w)
print(w.sum())

[45.29127938  0.42783519 45.58076606]
91.29988062995574
